### ISSUE TITLE
No es pot traduir sense cap rol

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/translateib#13]
Si s'entra a la pantalla de traducció amb un usuari que no disposa de cap rol, s'accedeix correctament (ok) però no es permet traduir.

Es pot provar de posar un text i donar-li a "Traduir" però no retorna cap resultat ni tampoc cap element de feedback que indiqui cap error.

PD: Després d'haver-ho provat d'aquesta manera, ara tampoc ens funciona la traducció amb rol... No sabem per què.
PD2: CREIM QUE POT SER UN PROBLEMA DE PLATA...

_2024-10-22 11:27:34,763 DEBUG [es.caib.translatorib.backend.controller.ViewTraducir] (default task-9) Respuesta del servidor: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>404 Not Found</title></head><body><h1>Not Found</h1><p>The requested URL was not found on this server.</p></body></html>_

_2024-10-22 11:27:34,763 ERROR [es.caib.translatorib.backend.controller.ViewTraducir] (default task-9) Error al realizar la traducción: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (String)"<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
</body></html>
"; line: 1, column: 2]
	at com.fasterxml.jackson.core.jackson-core@2.9.5.redhat-2//com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.jackson-core@2.9.5.redhat-2//com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:663)_

**Comment by scalafat-dgtic** [comment]
Ja està, era un problema intern de connexió
